### ISSUE TITLE
Make an nginx image with this config

### ISSUE THREAD

**Issue by cybermobile** [tsvcathed/nginx_lancache#1]
Hello,

Could you make a nginx server image with this config build in? So we can download the image and have this working out of the box? #

**Comment by jordandalley** [comment]
Hey,

I've thought about doing this, but the overheads in making an image with a nice simple install wizard aren't really worth it in the long run. That said, happy for someone else to pick up the batten on this.

I have about 30 of these deployed, and all I did was create an OVA in VMWare which I deploy out to sites. I just edit the known bits that change at each site, and it's easy enough to do :)

Cheers,
J.
