### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by sgeneralgrievous** [tsvcathed/nginx_lancache#10]
So I got everything pretty much working except for instance in windows when i do a check for updates on the error log of nginx i have this message:

2023/04/18 14:10:13 [error] 4797#4797: *4 open() "/usr/share/nginx/html/msdownload/update/software/crup/2009/11/msxml4-kb973688-enu_ccbcf042ade27866fd6c9b72767f9bc67ea54eb4.exe" failed (2: No such file or directory), client: 192.168.228.140, server: _, request: "HEAD /msdownload/update/software/crup/2009/11/msxml4-kb973688-enu_ccbcf042ade27866fd6c9b72767f9bc67ea54eb4.exe HTTP/1.1", host: "download.windowsupdate.com"

nginx is running as the nginx user. Is there another permission i need to give it?

Thankyou!

**Comment by sgeneralgrievous** [comment]
Im thinking its more to do with the stream module in nginx.

**Comment by sgeneralgrievous** [comment]
Yeah when i restart nginx I get an error: nginx: [emerg] unknown directive "stream" in /etc/nginx/nginx.conf:15

does this mean the stream module isnt activated?

**Comment by klightspeed** [comment]
What distribution are you using?  It sounds like nginx was not built `--with-stream`

**Comment by sgeneralgrievous** [comment]
> What distribution are you using? It sounds like nginx was not built `--with-stream`

Centos7, yeah so that was my problem. However what other modules are needed because now im getting an error like this:

nginx: [emerg] unknown directive "ssl_preread" in /etc/nginx/nginx.conf:27

does that mean im missing another module or something?

**Comment by sgeneralgrievous** [comment]
that was it, and a couple other modules. It works now.
