### ISSUE TITLE
is there a reason why "forwarders" are not set to something that works out of the box?

### ISSUE THREAD

**Issue by oktayaa** [tsvcathed/nginx_lancache#4]
In the docs you mention that something like 8.8.8.8 should be used but there are other (private) IPs in the config file.

**Comment by oktayaa** [comment]
By the way. I think they are called "resolvers" in the config.

**Comment by jordandalley** [comment]
Hi oktayaa,

Yeah I was using this GitHub repo as means of tracking my own config. Basically what the bind instance does here is intercepts known zones and points them at itself so they're passed through nginx, however nginx itself needs to resolve the true address. Basically the DNS servers that nginx points at can be anything that resolves the true destination address.

Resolvers, forwarders... One of those interchangeable terms. I'll update the docs, perhaps even push a new version that is better for public consumption and consistent with documentation.

Cheers :)

**Comment by oktayaa** [comment]
Cheers. It works great for my purposes. Actually your documentation is
pretty clear about it. What threw me off is that it's configured in two
places. I was working with a pfsense jail via it's web interface and
between shell being in a web browser and not being very familiar with plain
vi it took me a while to figure out I only edited the one line. :)

Thanks for the work.

**Comment by jordandalley** [comment]
Haha yeah, I'd imagine it would throw you off. It's a DNS resolver for the SNI stream and HTTP.. not sure why nginx doesn't just let you configure one DNS resolver globally.

Glad you've found it useful.

J.
